// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMfiYyLL-ZDR8DXhhBhnRXQS4pPTyvjCY',
    appId: '1:636917540969:web:f032ab55484b72f510daf8',
    messagingSenderId: '636917540969',
    projectId: 'pharmcam-4becd',
    authDomain: 'pharmcam-4becd.firebaseapp.com',
    storageBucket: 'pharmcam-4becd.firebasestorage.app',
    measurementId: 'G-E14TX0S8PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMes578rFtAwVk6Sma5RZnjS5hBBsMrl0',
    appId: '1:636917540969:android:2a6af279cc2f0ac810daf8',
    messagingSenderId: '636917540969',
    projectId: 'pharmcam-4becd',
    storageBucket: 'pharmcam-4becd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJz75WUXJsKSLMlCp0RhjqnhbmITZtgH0',
    appId: '1:636917540969:ios:3bc0d04dbe76647f10daf8',
    messagingSenderId: '636917540969',
    projectId: 'pharmcam-4becd',
    storageBucket: 'pharmcam-4becd.firebasestorage.app',
    iosBundleId: 'com.example.pharm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJz75WUXJsKSLMlCp0RhjqnhbmITZtgH0',
    appId: '1:636917540969:ios:3bc0d04dbe76647f10daf8',
    messagingSenderId: '636917540969',
    projectId: 'pharmcam-4becd',
    storageBucket: 'pharmcam-4becd.firebasestorage.app',
    iosBundleId: 'com.example.pharm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMfiYyLL-ZDR8DXhhBhnRXQS4pPTyvjCY',
    appId: '1:636917540969:web:a8376035ce54212210daf8',
    messagingSenderId: '636917540969',
    projectId: 'pharmcam-4becd',
    authDomain: 'pharmcam-4becd.firebaseapp.com',
    storageBucket: 'pharmcam-4becd.firebasestorage.app',
    measurementId: 'G-RE25KE77MX',
  );
}
